language : generic

sudo: required

services:
   - docker
  
before_install:
   - docker build -t likebat/react-test-app -f ./frontend/Dockerfile.dev ./frontend
  
script:
   - docker run -e CI=true likebat/react-test-app npm run test

after_success:
   - docker build -t likebat/docker-frontend ./frontend
   - docker build -t likebat/docker-backend ./backend
   - docker build -t likebat/docker-nginx   ./nginx


   - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  
   - docker push likebat/docker-frontend
   - docker push likebat/docker-backend
   - docker push likebat/docker-nginx

deploy:
   provider: elasticbeanstalk
   region : "ap-northeast-2"
   app: "docker-fullstack-app"
   env: "DockerFullstackApp-env-1"
   bucket_name : elasticbeanstalk-ap-northeast-2-467527922815
   bucket_path : "docker-fullstack-app"
   on:
    branch: main

   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_ACCESS_KEY
